import { table, hashKey, rangeKey, attribute, autoGeneratedHashKey } from '@aws/dynamodb-data-mapper-annotations';

function formatDate(date): string {
    const year = date.getFullYear().toString();
    const month = (date.getMonth() + 101).toString().substring(1);
    const day = (date.getDate() + 100).toString().substring(1);
    return `${year}-${month}-${day}`;
}

@table('article')
export class Article {

    @hashKey()
    id: string;

    @rangeKey({
        type: 'Date',
        defaultProvider: () => new Date(),
    })
    @attribute({
        indexKeyConfigurations: {
            ArticleCreateAt: 'RANGE',
        },
    })
    createAt: Date;

    @attribute()
    provider: string;

    @attribute({
        indexKeyConfigurations: {
            ArticleId: 'HASH',
        },
    })
    title: string;

    @attribute()
    link: string;

    @attribute()
    image: string;

}
